### PR TITLE
Refactoring hearth beat timeout cb.

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

### CODE REVIEW

**Comment by nxp-wayne** [comment]
What's the purpose of the refactor? Is there any issue in original implementation?
Putting all control into dispatcher thread can avoid contents of multiple threads.

**Comment by Hadatko** [comment]
Refactored code: in .h updated macro to be misra complained. 
in .c use existing function instead of writting same code as function implementation.

**Comment by nxp-wayne** [comment]
Makes sense, thank you.

**Review by mcuxsusan — APPROVED** [review]
According to feedback from the developer, the change is OK. Thank you.

**Pull request merged**
